name: Project

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build with Cmake
        run: cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -S$(pwd) -B$(pwd)/build -G "Unix Makefiles" && cmake --build build --config Debug --target all -j 10 --verbose
      - name: Run tests
        run: cd build && raytracer/tests/tests